/**
 * Writes the recorded vendor fixtures into `packages/adapters` (ADR 13).
 *
 * Run it with `pnpm record:fixtures` from the repository root, which invokes
 * this and then formats what it wrote. The command is idempotent: same inputs,
 * same bytes, so a run on an unchanged tree leaves the working tree clean. CI
 * depends on that — it re-records and fails on any diff, which is the guard that
 * keeps the committed fixtures honest and replaces the manual procedure that
 * used to live in `packages/adapters/src/testing/README.md`.
 *
 * Why this lives in `packages/simulator` and not in `packages/adapters`: ADR 11
 * forbids adapters from depending on the simulator in production *or* in tests,
 * because a fixture generated by importing the producer into the consumer's test
 * suite would let a defect present in both cancel out and still pass. The
 * simulator owns the authoritative dialect generators, so it owns the step that
 * emits them. What crosses the package boundary is bytes on disk, not a module
 * import, and the arrow points one way.
 *
 * This is the executable boundary for recording: the one file here that touches
 * the filesystem and sets an exit code. `fixtureSet.ts` stays pure.
 */
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import {
  RECORDING_FLEET_SIZE,
  RECORDING_INSTANT_MS,
  RECORDING_SEED,
  buildRecordedFixtures,
  serializeFixture,
  type RecordedFixture,
} from "./fixtureSet.ts";

/** Repository root, resolved from this file rather than from the process's cwd. */
const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "..", "..");

/** The adapters module whose `FIXTURE_RECORDING` must agree with the pinned inputs here. */
const FIXTURES_MODULE = join(REPO_ROOT, "packages", "adapters", "src", "testing", "fixtures.ts");

/**
 * Absolute path of one fixture file.
 *
 * Coupling: `packages/adapters/src/testing/fixtures.ts` statically imports
 * exactly these paths (ADR 11). Moving them means moving that import, this
 * function, and the CI diff's path filter in one commit.
 */
function fixturePath(fixture: RecordedFixture): string {
  return join(
    REPO_ROOT,
    "packages",
    "adapters",
    "src",
    "vendors",
    fixture.vendor.toLowerCase(),
    "__fixtures__",
    `${fixture.name}.json`,
  );
}

/**
 * Fails the run when the adapters-side provenance constants have drifted from
 * the pinned inputs used here.
 *
 * `FIXTURE_RECORDING` is what a consuming test trusts when it uses the pinned
 * instant as `receivedAt` instead of reading a clock. If it says one thing and
 * the recorder does another, every fixture is still byte-perfect and every
 * consumer is still wrong — a failure the diff guard cannot see, because the
 * payloads themselves would not change. A textual check is enough and keeps this
 * package free of an import into adapters.
 */
async function assertProvenanceAgrees(): Promise<void> {
  // Numeric separators are stripped first so `1_755_600_000_000` and
  // `1755600000000` compare equal; both are legal and the choice is cosmetic.
  const source = (await readFile(FIXTURES_MODULE, "utf8")).replace(/(\d)_(?=\d)/g, "$1");
  const expectations: readonly (readonly [string, string])[] = [
    ["seed", `seed: ${String(RECORDING_SEED)},`],
    ["fleetSize", `fleetSize: ${String(RECORDING_FLEET_SIZE)},`],
    ["instantMs", `instantMs: ${String(RECORDING_INSTANT_MS)},`],
  ];

  const missing = expectations.filter(([, needle]) => !source.includes(needle));
  if (missing.length > 0) {
    throw new Error(
      `packages/adapters/src/testing/fixtures.ts does not declare the inputs this recorder ` +
        `uses: ${missing.map(([field]) => field).join(", ")}. Update FIXTURE_RECORDING and ` +
        `fixtureSet.ts together — a fixture is only trustworthy if its stated provenance is true.`,
    );
  }
}

/** Records every fixture, returning the paths written, repository-relative. */
export async function recordFixtures(): Promise<readonly string[]> {
  await assertProvenanceAgrees();

  const written: string[] = [];
  for (const fixture of buildRecordedFixtures()) {
    const file = fixturePath(fixture);
    await writeFile(file, serializeFixture(fixture), "utf8");
    written.push(file.slice(REPO_ROOT.length + 1));
  }
  return written;
}

/** True when Node was told to run this module, rather than something importing it. */
function isProcessEntryPoint(): boolean {
  const entry = process.argv[1];
  return entry !== undefined && import.meta.url === pathToFileURL(entry).href;
}

if (isProcessEntryPoint()) {
  try {
    const written = await recordFixtures();
    process.stdout.write(`${written.map((file) => `  ${file}`).join("\n")}\n`);
    process.stdout.write(`Recorded ${String(written.length)} vendor fixture(s).\n`);
  } catch (error) {
    process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
    process.exitCode = 1;
  }
}
