import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

import { SHARED_TOKENS, THEME_TOKENS } from "../packages/web/src/styles/tokens.ts";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUTPUT = path.join(ROOT, "packages/web/src/styles/tokens.css");

function renderDeclarations(tokens) {
  return Object.entries(tokens)
    .map(([name, value]) => `  ${name}: ${value};`)
    .join("\n");
}

/** Renders the committed CSS artifact from the one authored TypeScript token source. */
export function renderTokensCss({ shared, themes }) {
  return `/* Generated by scripts/generateWebTokens.mjs from src/styles/tokens.ts. */

:root {
${renderDeclarations(shared)}
}

:root,
[data-theme="dark"] {
  color-scheme: dark;
${renderDeclarations(themes.dark)}
}

[data-theme="light"] {
  color-scheme: light;
${renderDeclarations(themes.light)}
}
`;
}

const generated = renderTokensCss({ shared: SHARED_TOKENS, themes: THEME_TOKENS });

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  if (process.argv.includes("--check")) {
    const current = await readFile(OUTPUT, "utf8");
    if (current !== generated) {
      console.error("packages/web/src/styles/tokens.css is stale; run pnpm tokens:generate.");
      process.exitCode = 1;
    }
  } else {
    await writeFile(OUTPUT, generated);
  }
}
