import assert from "node:assert/strict";
import test from "node:test";

import { renderTokensCss } from "./generateWebTokens.mjs";

test("renders shared and tenant tokens from one authored value set", () => {
  const css = renderTokensCss({
    shared: { "--space-1": "4px" },
    themes: {
      dark: { "--bg": "#111111" },
      light: { "--bg": "#eeeeee" },
    },
  });

  assert.equal(
    css,
    `/* Generated by scripts/generateWebTokens.mjs from src/styles/tokens.ts. */

:root {
  --space-1: 4px;
}

:root,
[data-theme="dark"] {
  color-scheme: dark;
  --bg: #111111;
}

[data-theme="light"] {
  color-scheme: light;
  --bg: #eeeeee;
}
`,
  );
});
