import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

import { format, resolveConfig } from "prettier";

import { SHARED_TOKENS, THEME_TOKENS } from "../packages/web/src/styles/tokens.ts";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUTPUT = path.join(ROOT, "packages/web/src/styles/tokens.css");
const PRETTIER_CONFIG = (await resolveConfig(OUTPUT)) ?? {};

function renderDeclarations(tokens) {
  return Object.entries(tokens)
    .map(([name, value]) => `  ${name}: ${value};`)
    .join("\n");
}

function assertThemeTokenParity(themes) {
  const darkNames = Object.keys(themes.dark).sort();
  const lightNames = Object.keys(themes.light).sort();
  if (darkNames.join("\n") !== lightNames.join("\n")) {
    throw new Error(
      "Dark and light themes must define the same custom properties; a missing light value would inherit the dark :root fallback.",
    );
  }
}

/** Renders the committed CSS artifact from the one authored TypeScript token source. */
export async function renderTokensCss({ shared, themes }) {
  assertThemeTokenParity(themes);
  const css = `/* Generated by scripts/generateWebTokens.mjs from src/styles/tokens.ts. */

:root {
${renderDeclarations(shared)}
}

:root,
[data-theme="dark"] {
  color-scheme: dark;
${renderDeclarations(themes.dark)}
}

[data-theme="light"] {
  color-scheme: light;
${renderDeclarations(themes.light)}
}
`;
  return format(css, { ...PRETTIER_CONFIG, parser: "css" });
}

const generated = await renderTokensCss({ shared: SHARED_TOKENS, themes: THEME_TOKENS });

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  if (process.argv.includes("--check")) {
    const current = await readFile(OUTPUT, "utf8");
    if (current !== generated) {
      console.error(
        "packages/web/src/styles/tokens.css is stale; run pnpm --filter web tokens:generate.",
      );
      process.exitCode = 1;
    }
  } else {
    await writeFile(OUTPUT, generated);
  }
}
